export * from 'is-what'
export * from 'merge-anything'

export * from './code-highlight.lazy.js'
export * from './diff.js'
export * from './hashObj.js'
export * from './isEqual.js'
export * from './map-apply-max-size.js'
export * from './memoize.js'
export * from './stringify.js'
export * from './uid.js'
