export * from 'is-what'
export * from 'deep-object-diff'
export * from 'merge-anything'

export * from './code-highlight.lazy.js'
export * from './hashObj.js'
export * from './equality.js'
export * from './map-apply-max-size.js'
export * from './memoize.js'
export * from './stringify.js'
export * from './uid.js'
